#include </usr/lib/avr/include/avr/io.h>
#include "../../../Unity-master/src/unity.h"
#include <stdio.h>

extern int check;
extern int verify[2];

int main_test(void);
void buzzer_on (void);
void buzzer_off (void);
void buzzer_pin_config(void);
void timer4_init(void);
void init_devices(void);


void test_buzzer_on()
{
buzzer_on();
TEST_ASSERT_EQUAL_INT (0x08, PORTC);
}

void test_buzzer_off()
{
buzzer_off();
TEST_ASSERT_EQUAL_INT (0x00, PORTC);
}

void test_buzzer_pin_config()
{
buzzer_pin_config();
TEST_ASSERT_EQUAL_INT(0x08,DDRC);
TEST_ASSERT_EQUAL_INT(0x00,PORTC);
}

void test_timer4_init()
{
timer4_init();
TEST_ASSERT_EQUAL_INT(0x1F,TCNT4H);
TEST_ASSERT_EQUAL_INT(0x01,TCNT4L);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CL);
TEST_ASSERT_EQUAL_INT(0x00,ICR4H);
TEST_ASSERT_EQUAL_INT(0x00,ICR4L);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4A);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4C);
TEST_ASSERT_EQUAL_INT(0x04,TCCR4B);
}

void test_init_devices()
{
init_devices();
TEST_ASSERT_EQUAL_INT(0x08,DDRC);
TEST_ASSERT_EQUAL_INT(0x00,PORTC);
TEST_ASSERT_EQUAL_INT(0x1F,TCNT4H);
TEST_ASSERT_EQUAL_INT(0x01,TCNT4L);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CL);
TEST_ASSERT_EQUAL_INT(0x00,ICR4H);
TEST_ASSERT_EQUAL_INT(0x00,ICR4L);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4A);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4C);
TEST_ASSERT_EQUAL_INT(0x04,TCCR4B);
TEST_ASSERT_EQUAL_INT(0x01,TIMSK4);
}


void test_main(void) 
{
main_test();
TEST_ASSERT_EQUAL_INT(0x08,DDRC);
TEST_ASSERT_EQUAL_INT(0x1F,TCNT4H);
TEST_ASSERT_EQUAL_INT(0x01,TCNT4L);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4AL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4BL);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CH);
TEST_ASSERT_EQUAL_INT(0x00,OCR4CL);
TEST_ASSERT_EQUAL_INT(0x00,ICR4H);
TEST_ASSERT_EQUAL_INT(0x00,ICR4L);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4A);
TEST_ASSERT_EQUAL_INT(0x00,TCCR4C);
TEST_ASSERT_EQUAL_INT(0x04,TCCR4B);
TEST_ASSERT_EQUAL_INT(0x01,TIMSK4);
TEST_ASSERT_EQUAL_INT(2,check);
TEST_ASSERT_EQUAL_INT(0x00,verify[0]);
TEST_ASSERT_EQUAL_INT(0x08,verify[1]);

} 

int main()
{
UNITY_BEGIN();
RUN_TEST(test_main);
RUN_TEST(test_buzzer_off);
RUN_TEST(test_buzzer_on);
RUN_TEST(test_init_devices);
RUN_TEST(test_timer4_init);
RUN_TEST(test_buzzer_pin_config);
}
