/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../../../Unity-master/src/unity.h"
#include "../../../CMock/src/cmock.c"
#include "MockTBT7.h"

static const char* CMockString_delay_new_ms = "delay_new_ms";
static const char* CMockString_m = "m";

typedef struct _CMOCK_delay_new_ms_CALL_INSTANCE
{
  int LineNumber;
  int Expected_m;

} CMOCK_delay_new_ms_CALL_INSTANCE;

static struct MockTBT7Instance
{
  int delay_new_ms_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE delay_new_ms_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTBT7_Verify(void)
{
  int cmock_line = TEST_LINE_NUM;
  if (Mock.delay_new_ms_IgnoreBool)
    Mock.delay_new_ms_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_delay_new_ms);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.delay_new_ms_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockTBT7_Init(void)
{
  MockTBT7_Destroy();
}

void MockTBT7_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void delay_new_ms(int m)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_delay_new_ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_delay_new_ms);
  cmock_call_instance = (CMOCK_delay_new_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.delay_new_ms_CallInstance);
  Mock.delay_new_ms_CallInstance = CMock_Guts_MemNext(Mock.delay_new_ms_CallInstance);
  if (Mock.delay_new_ms_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_delay_new_ms,CMockString_m);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_m, m, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_delay_new_ms(CMOCK_delay_new_ms_CALL_INSTANCE* cmock_call_instance, int m)
{
  cmock_call_instance->Expected_m = m;
}

void delay_new_ms_CMockIgnore(void)
{
  Mock.delay_new_ms_IgnoreBool = (int)1;
}

void delay_new_ms_CMockExpect(int cmock_line, int m)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_delay_new_ms_CALL_INSTANCE));
  CMOCK_delay_new_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_delay_new_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.delay_new_ms_CallInstance = CMock_Guts_MemChain(Mock.delay_new_ms_CallInstance, cmock_guts_index);
  Mock.delay_new_ms_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_delay_new_ms(cmock_call_instance, m);
  UNITY_CLR_DETAILS();
}

