/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOTION_CONTROL_H
#define _MOCKMOTION_CONTROL_H

#include "Motion_Control.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockMotion_Control_Init(void);
void MockMotion_Control_Destroy(void);
void MockMotion_Control_Verify(void);




#define motion_pin_config_Expect() motion_pin_config_CMockExpect(__LINE__)
void motion_pin_config_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define port_init_Expect() port_init_CMockExpect(__LINE__)
void port_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define motion_set_Expect(Direction) motion_set_CMockExpect(__LINE__, Direction)
void motion_set_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char Direction);
#define forward_Expect() forward_CMockExpect(__LINE__)
void forward_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define back_Expect() back_CMockExpect(__LINE__)
void back_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define left_Expect() left_CMockExpect(__LINE__)
void left_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define right_Expect() right_CMockExpect(__LINE__)
void right_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define soft_left_Expect() soft_left_CMockExpect(__LINE__)
void soft_left_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define soft_right_Expect() soft_right_CMockExpect(__LINE__)
void soft_right_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define stop_Expect() stop_CMockExpect(__LINE__)
void stop_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define soft_left_2_Expect() soft_left_2_CMockExpect(__LINE__)
void soft_left_2_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define soft_right_2_Expect() soft_right_2_CMockExpect(__LINE__)
void soft_right_2_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define init_devices_Expect() init_devices_CMockExpect(__LINE__)
void init_devices_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define main_1_ExpectAndReturn(cmock_retval) main_1_CMockExpectAndReturn(__LINE__, cmock_retval)
void main_1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);

#endif
