/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockMotion_Control.h"

static const char* CMockString_Direction = "Direction";
static const char* CMockString_back = "back";
static const char* CMockString_forward = "forward";
static const char* CMockString_init_devices = "init_devices";
static const char* CMockString_left = "left";
static const char* CMockString_main_1 = "main_1";
static const char* CMockString_motion_pin_config = "motion_pin_config";
static const char* CMockString_motion_set = "motion_set";
static const char* CMockString_port_init = "port_init";
static const char* CMockString_right = "right";
static const char* CMockString_soft_left = "soft_left";
static const char* CMockString_soft_left_2 = "soft_left_2";
static const char* CMockString_soft_right = "soft_right";
static const char* CMockString_soft_right_2 = "soft_right_2";
static const char* CMockString_stop = "stop";

typedef struct _CMOCK_motion_pin_config_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_motion_pin_config_CALL_INSTANCE;

typedef struct _CMOCK_port_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_port_init_CALL_INSTANCE;

typedef struct _CMOCK_motion_set_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_Direction;

} CMOCK_motion_set_CALL_INSTANCE;

typedef struct _CMOCK_forward_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_forward_CALL_INSTANCE;

typedef struct _CMOCK_back_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_back_CALL_INSTANCE;

typedef struct _CMOCK_left_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_left_CALL_INSTANCE;

typedef struct _CMOCK_right_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_right_CALL_INSTANCE;

typedef struct _CMOCK_soft_left_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_soft_left_CALL_INSTANCE;

typedef struct _CMOCK_soft_right_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_soft_right_CALL_INSTANCE;

typedef struct _CMOCK_stop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_stop_CALL_INSTANCE;

typedef struct _CMOCK_soft_left_2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_soft_left_2_CALL_INSTANCE;

typedef struct _CMOCK_soft_right_2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_soft_right_2_CALL_INSTANCE;

typedef struct _CMOCK_init_devices_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_init_devices_CALL_INSTANCE;

typedef struct _CMOCK_main_1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;

} CMOCK_main_1_CALL_INSTANCE;

static struct MockMotion_ControlInstance
{
  CMOCK_MEM_INDEX_TYPE motion_pin_config_CallInstance;
  CMOCK_MEM_INDEX_TYPE port_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE motion_set_CallInstance;
  CMOCK_MEM_INDEX_TYPE forward_CallInstance;
  CMOCK_MEM_INDEX_TYPE back_CallInstance;
  CMOCK_MEM_INDEX_TYPE left_CallInstance;
  CMOCK_MEM_INDEX_TYPE right_CallInstance;
  CMOCK_MEM_INDEX_TYPE soft_left_CallInstance;
  CMOCK_MEM_INDEX_TYPE soft_right_CallInstance;
  CMOCK_MEM_INDEX_TYPE stop_CallInstance;
  CMOCK_MEM_INDEX_TYPE soft_left_2_CallInstance;
  CMOCK_MEM_INDEX_TYPE soft_right_2_CallInstance;
  CMOCK_MEM_INDEX_TYPE init_devices_CallInstance;
  CMOCK_MEM_INDEX_TYPE main_1_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockMotion_Control_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_motion_pin_config);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.motion_pin_config_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_port_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.port_init_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_motion_set);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.motion_set_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_forward);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.forward_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_back);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.back_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_left);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.left_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_right);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.right_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_soft_left);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.soft_left_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_soft_right);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.soft_right_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_stop);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.stop_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_soft_left_2);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.soft_left_2_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_soft_right_2);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.soft_right_2_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_init_devices);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.init_devices_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_main_1);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.main_1_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockMotion_Control_Init(void)
{
  MockMotion_Control_Destroy();
}

void MockMotion_Control_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void motion_pin_config(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_motion_pin_config_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_motion_pin_config);
  cmock_call_instance = (CMOCK_motion_pin_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.motion_pin_config_CallInstance);
  Mock.motion_pin_config_CallInstance = CMock_Guts_MemNext(Mock.motion_pin_config_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void motion_pin_config_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_motion_pin_config_CALL_INSTANCE));
  CMOCK_motion_pin_config_CALL_INSTANCE* cmock_call_instance = (CMOCK_motion_pin_config_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.motion_pin_config_CallInstance = CMock_Guts_MemChain(Mock.motion_pin_config_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void port_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_port_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_port_init);
  cmock_call_instance = (CMOCK_port_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.port_init_CallInstance);
  Mock.port_init_CallInstance = CMock_Guts_MemNext(Mock.port_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void port_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_port_init_CALL_INSTANCE));
  CMOCK_port_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_port_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.port_init_CallInstance = CMock_Guts_MemChain(Mock.port_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void motion_set(unsigned char Direction)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_motion_set_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_motion_set);
  cmock_call_instance = (CMOCK_motion_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.motion_set_CallInstance);
  Mock.motion_set_CallInstance = CMock_Guts_MemNext(Mock.motion_set_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_motion_set,CMockString_Direction);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_Direction, Direction, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_motion_set(CMOCK_motion_set_CALL_INSTANCE* cmock_call_instance, unsigned char Direction)
{
  cmock_call_instance->Expected_Direction = Direction;
}

void motion_set_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char Direction)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_motion_set_CALL_INSTANCE));
  CMOCK_motion_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_motion_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.motion_set_CallInstance = CMock_Guts_MemChain(Mock.motion_set_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_motion_set(cmock_call_instance, Direction);
  UNITY_CLR_DETAILS();
}

void forward(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_forward_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_forward);
  cmock_call_instance = (CMOCK_forward_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.forward_CallInstance);
  Mock.forward_CallInstance = CMock_Guts_MemNext(Mock.forward_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void forward_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_forward_CALL_INSTANCE));
  CMOCK_forward_CALL_INSTANCE* cmock_call_instance = (CMOCK_forward_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.forward_CallInstance = CMock_Guts_MemChain(Mock.forward_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void back(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_back_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_back);
  cmock_call_instance = (CMOCK_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.back_CallInstance);
  Mock.back_CallInstance = CMock_Guts_MemNext(Mock.back_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void back_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_back_CALL_INSTANCE));
  CMOCK_back_CALL_INSTANCE* cmock_call_instance = (CMOCK_back_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.back_CallInstance = CMock_Guts_MemChain(Mock.back_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void left(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_left_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_left);
  cmock_call_instance = (CMOCK_left_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.left_CallInstance);
  Mock.left_CallInstance = CMock_Guts_MemNext(Mock.left_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void left_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_left_CALL_INSTANCE));
  CMOCK_left_CALL_INSTANCE* cmock_call_instance = (CMOCK_left_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.left_CallInstance = CMock_Guts_MemChain(Mock.left_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void right(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_right_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_right);
  cmock_call_instance = (CMOCK_right_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.right_CallInstance);
  Mock.right_CallInstance = CMock_Guts_MemNext(Mock.right_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void right_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_right_CALL_INSTANCE));
  CMOCK_right_CALL_INSTANCE* cmock_call_instance = (CMOCK_right_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.right_CallInstance = CMock_Guts_MemChain(Mock.right_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void soft_left(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_soft_left_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_soft_left);
  cmock_call_instance = (CMOCK_soft_left_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.soft_left_CallInstance);
  Mock.soft_left_CallInstance = CMock_Guts_MemNext(Mock.soft_left_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void soft_left_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_soft_left_CALL_INSTANCE));
  CMOCK_soft_left_CALL_INSTANCE* cmock_call_instance = (CMOCK_soft_left_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.soft_left_CallInstance = CMock_Guts_MemChain(Mock.soft_left_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void soft_right(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_soft_right_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_soft_right);
  cmock_call_instance = (CMOCK_soft_right_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.soft_right_CallInstance);
  Mock.soft_right_CallInstance = CMock_Guts_MemNext(Mock.soft_right_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void soft_right_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_soft_right_CALL_INSTANCE));
  CMOCK_soft_right_CALL_INSTANCE* cmock_call_instance = (CMOCK_soft_right_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.soft_right_CallInstance = CMock_Guts_MemChain(Mock.soft_right_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void stop(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_stop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_stop);
  cmock_call_instance = (CMOCK_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.stop_CallInstance);
  Mock.stop_CallInstance = CMock_Guts_MemNext(Mock.stop_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void stop_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stop_CALL_INSTANCE));
  CMOCK_stop_CALL_INSTANCE* cmock_call_instance = (CMOCK_stop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stop_CallInstance = CMock_Guts_MemChain(Mock.stop_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void soft_left_2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_soft_left_2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_soft_left_2);
  cmock_call_instance = (CMOCK_soft_left_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.soft_left_2_CallInstance);
  Mock.soft_left_2_CallInstance = CMock_Guts_MemNext(Mock.soft_left_2_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void soft_left_2_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_soft_left_2_CALL_INSTANCE));
  CMOCK_soft_left_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_soft_left_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.soft_left_2_CallInstance = CMock_Guts_MemChain(Mock.soft_left_2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void soft_right_2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_soft_right_2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_soft_right_2);
  cmock_call_instance = (CMOCK_soft_right_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.soft_right_2_CallInstance);
  Mock.soft_right_2_CallInstance = CMock_Guts_MemNext(Mock.soft_right_2_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void soft_right_2_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_soft_right_2_CALL_INSTANCE));
  CMOCK_soft_right_2_CALL_INSTANCE* cmock_call_instance = (CMOCK_soft_right_2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.soft_right_2_CallInstance = CMock_Guts_MemChain(Mock.soft_right_2_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void init_devices(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_devices_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_devices);
  cmock_call_instance = (CMOCK_init_devices_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_devices_CallInstance);
  Mock.init_devices_CallInstance = CMock_Guts_MemNext(Mock.init_devices_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void init_devices_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_devices_CALL_INSTANCE));
  CMOCK_init_devices_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_devices_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_devices_CallInstance = CMock_Guts_MemChain(Mock.init_devices_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

int main_1(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_main_1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_main_1);
  cmock_call_instance = (CMOCK_main_1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.main_1_CallInstance);
  Mock.main_1_CallInstance = CMock_Guts_MemNext(Mock.main_1_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void main_1_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_main_1_CALL_INSTANCE));
  CMOCK_main_1_CALL_INSTANCE* cmock_call_instance = (CMOCK_main_1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.main_1_CallInstance = CMock_Guts_MemChain(Mock.main_1_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

