/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFUNCTIONS_H
#define _MOCKFUNCTIONS_H

#include "../functions.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfunctions_Init(void);
void Mockfunctions_Destroy(void);
void Mockfunctions_Verify(void);




#define print_sensor_Expect(row, coloumn, channel) print_sensor_CMockExpect(__LINE__, row, coloumn, channel)
void print_sensor_CMockExpect(int cmock_line, char row, char coloumn, unsigned char channel);

#endif
