/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFUNCTION1_H
#define _MOCKFUNCTION1_H

#include "../function1.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockfunction1_Init(void);
void Mockfunction1_Destroy(void);
void Mockfunction1_Verify(void);




#define ADC_conversion_ExpectAndReturn(cmock_arg1, cmock_retval) ADC_conversion_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_retval)
void ADC_conversion_CMockExpectAndReturn(int cmock_line, unsigned char cmock_arg1, unsigned char cmock_to_return);
#define Sharp_GP2D12_estimation_ExpectAndReturn(adc_reading, cmock_retval) Sharp_GP2D12_estimation_CMockExpectAndReturn(__LINE__, adc_reading, cmock_retval)
void Sharp_GP2D12_estimation_CMockExpectAndReturn(int cmock_line, unsigned char adc_reading, unsigned int cmock_to_return);

#endif
