/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MS_DELAY_H
#define _MOCK_MS_DELAY_H

#include "../_ms_delay.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_ms_delay_Init(void);
void Mock_ms_delay_Destroy(void);
void Mock_ms_delay_Verify(void);




#define _delay_ms_Ignore() _delay_ms_CMockIgnore()
void _delay_ms_CMockIgnore(void);
#define _delay_ms_Expect(__ms) _delay_ms_CMockExpect(__LINE__, __ms)
void _delay_ms_CMockExpect(int cmock_line, double __ms);

#endif
