/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../../../Unity-master/src/unity.h"
#include "../../../CMock/src/cmock.c"
#include "MockADC_Function_Header.h"

static const char* CMockString_ADC_Conversion = "ADC_Conversion";
static const char* CMockString_Sharp_GP2D12_estimation = "Sharp_GP2D12_estimation";
static const char* CMockString_adc_reading = "adc_reading";
static const char* CMockString_channel = "channel";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_coloumn = "coloumn";
static const char* CMockString_digits = "digits";
static const char* CMockString_lcd_print = "lcd_print";
static const char* CMockString_print_sensor = "print_sensor";
static const char* CMockString_row = "row";
static const char* CMockString_value = "value";

typedef struct _CMOCK_ADC_Conversion_CALL_INSTANCE
{
  int LineNumber;
  unsigned char ReturnVal;
  unsigned char Expected_cmock_arg1;

} CMOCK_ADC_Conversion_CALL_INSTANCE;

typedef struct _CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE
{
  int LineNumber;
  unsigned int ReturnVal;
  unsigned char Expected_adc_reading;

} CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE;

typedef struct _CMOCK_print_sensor_CALL_INSTANCE
{
  int LineNumber;
  char Expected_row;
  char Expected_coloumn;
  unsigned char Expected_channel;

} CMOCK_print_sensor_CALL_INSTANCE;

typedef struct _CMOCK_lcd_print_CALL_INSTANCE
{
  int LineNumber;
  char Expected_row;
  char Expected_coloumn;
  unsigned int Expected_value;
  int Expected_digits;

} CMOCK_lcd_print_CALL_INSTANCE;

static struct MockADC_Function_HeaderInstance
{
  CMOCK_MEM_INDEX_TYPE ADC_Conversion_CallInstance;
  CMOCK_MEM_INDEX_TYPE Sharp_GP2D12_estimation_CallInstance;
  CMOCK_MEM_INDEX_TYPE print_sensor_CallInstance;
  CMOCK_MEM_INDEX_TYPE lcd_print_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockADC_Function_Header_Verify(void)
{
  int cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_Conversion);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_Conversion_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_Sharp_GP2D12_estimation);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Sharp_GP2D12_estimation_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_print_sensor);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.print_sensor_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_lcd_print);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.lcd_print_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockADC_Function_Header_Init(void)
{
  MockADC_Function_Header_Destroy();
}

void MockADC_Function_Header_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

unsigned char ADC_Conversion(unsigned char cmock_arg1)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_ADC_Conversion_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ADC_Conversion);
  cmock_call_instance = (CMOCK_ADC_Conversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_Conversion_CallInstance);
  Mock.ADC_Conversion_CallInstance = CMock_Guts_MemNext(Mock.ADC_Conversion_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_ADC_Conversion,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ADC_Conversion(CMOCK_ADC_Conversion_CALL_INSTANCE* cmock_call_instance, unsigned char cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void ADC_Conversion_CMockExpectAndReturn(int cmock_line, unsigned char cmock_arg1, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_Conversion_CALL_INSTANCE));
  CMOCK_ADC_Conversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_Conversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_Conversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_Conversion_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ADC_Conversion(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

unsigned int Sharp_GP2D12_estimation(unsigned char adc_reading)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sharp_GP2D12_estimation);
  cmock_call_instance = (CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sharp_GP2D12_estimation_CallInstance);
  Mock.Sharp_GP2D12_estimation_CallInstance = CMock_Guts_MemNext(Mock.Sharp_GP2D12_estimation_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Sharp_GP2D12_estimation,CMockString_adc_reading);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_adc_reading, adc_reading, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Sharp_GP2D12_estimation(CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance, unsigned char adc_reading)
{
  cmock_call_instance->Expected_adc_reading = adc_reading;
}

void Sharp_GP2D12_estimation_CMockExpectAndReturn(int cmock_line, unsigned char adc_reading, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE));
  CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sharp_GP2D12_estimation_CallInstance = CMock_Guts_MemChain(Mock.Sharp_GP2D12_estimation_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Sharp_GP2D12_estimation(cmock_call_instance, adc_reading);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void print_sensor(char row, char coloumn, unsigned char channel)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_print_sensor_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_print_sensor);
  cmock_call_instance = (CMOCK_print_sensor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.print_sensor_CallInstance);
  Mock.print_sensor_CallInstance = CMock_Guts_MemNext(Mock.print_sensor_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_print_sensor,CMockString_row);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_row, row, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_print_sensor,CMockString_coloumn);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_coloumn, coloumn, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_print_sensor,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_print_sensor(CMOCK_print_sensor_CALL_INSTANCE* cmock_call_instance, char row, char coloumn, unsigned char channel)
{
  cmock_call_instance->Expected_row = row;
  cmock_call_instance->Expected_coloumn = coloumn;
  cmock_call_instance->Expected_channel = channel;
}

void print_sensor_CMockExpect(int cmock_line, char row, char coloumn, unsigned char channel)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_print_sensor_CALL_INSTANCE));
  CMOCK_print_sensor_CALL_INSTANCE* cmock_call_instance = (CMOCK_print_sensor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.print_sensor_CallInstance = CMock_Guts_MemChain(Mock.print_sensor_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_print_sensor(cmock_call_instance, row, coloumn, channel);
  UNITY_CLR_DETAILS();
}

void lcd_print(char row, char coloumn, unsigned int value, int digits)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_lcd_print_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_lcd_print);
  cmock_call_instance = (CMOCK_lcd_print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.lcd_print_CallInstance);
  Mock.lcd_print_CallInstance = CMock_Guts_MemNext(Mock.lcd_print_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_lcd_print,CMockString_row);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_row, row, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_lcd_print,CMockString_coloumn);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_coloumn, coloumn, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_lcd_print,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_lcd_print,CMockString_digits);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_digits, digits, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_lcd_print(CMOCK_lcd_print_CALL_INSTANCE* cmock_call_instance, char row, char coloumn, unsigned int value, int digits)
{
  cmock_call_instance->Expected_row = row;
  cmock_call_instance->Expected_coloumn = coloumn;
  cmock_call_instance->Expected_value = value;
  cmock_call_instance->Expected_digits = digits;
}

void lcd_print_CMockExpect(int cmock_line, char row, char coloumn, unsigned int value, int digits)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_lcd_print_CALL_INSTANCE));
  CMOCK_lcd_print_CALL_INSTANCE* cmock_call_instance = (CMOCK_lcd_print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.lcd_print_CallInstance = CMock_Guts_MemChain(Mock.lcd_print_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_lcd_print(cmock_call_instance, row, coloumn, value, digits);
  UNITY_CLR_DETAILS();
}

