/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "../../../Unity-master/src/unity.h"
#include "../../../CMock/src/cmock.c"
#include "Mockfunction1.h"

static const char* CMockString_ADC_conversion = "ADC_conversion";
static const char* CMockString_Sharp_GP2D12_estimation = "Sharp_GP2D12_estimation";
static const char* CMockString_adc_reading = "adc_reading";
static const char* CMockString_cmock_arg1 = "cmock_arg1";

typedef struct _CMOCK_ADC_conversion_CALL_INSTANCE
{
  int LineNumber;
  unsigned char ReturnVal;
  unsigned char Expected_cmock_arg1;

} CMOCK_ADC_conversion_CALL_INSTANCE;

typedef struct _CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE
{
  int LineNumber;
  unsigned int ReturnVal;
  unsigned char Expected_adc_reading;

} CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE;

static struct Mockfunction1Instance
{
  CMOCK_MEM_INDEX_TYPE ADC_conversion_CallInstance;
  CMOCK_MEM_INDEX_TYPE Sharp_GP2D12_estimation_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockfunction1_Verify(void)
{
  int cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_conversion);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_conversion_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_Sharp_GP2D12_estimation);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Sharp_GP2D12_estimation_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockfunction1_Init(void)
{
  Mockfunction1_Destroy();
}

void Mockfunction1_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

unsigned char ADC_conversion(unsigned char cmock_arg1)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_ADC_conversion_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ADC_conversion);
  cmock_call_instance = (CMOCK_ADC_conversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_conversion_CallInstance);
  Mock.ADC_conversion_CallInstance = CMock_Guts_MemNext(Mock.ADC_conversion_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_ADC_conversion,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ADC_conversion(CMOCK_ADC_conversion_CALL_INSTANCE* cmock_call_instance, unsigned char cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void ADC_conversion_CMockExpectAndReturn(int cmock_line, unsigned char cmock_arg1, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_conversion_CALL_INSTANCE));
  CMOCK_ADC_conversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_conversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_conversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_conversion_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_ADC_conversion(cmock_call_instance, cmock_arg1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

unsigned int Sharp_GP2D12_estimation(unsigned char adc_reading)
{
  int cmock_line = TEST_LINE_NUM;
  CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sharp_GP2D12_estimation);
  cmock_call_instance = (CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sharp_GP2D12_estimation_CallInstance);
  Mock.Sharp_GP2D12_estimation_CallInstance = CMock_Guts_MemNext(Mock.Sharp_GP2D12_estimation_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Sharp_GP2D12_estimation,CMockString_adc_reading);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_adc_reading, adc_reading, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Sharp_GP2D12_estimation(CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance, unsigned char adc_reading)
{
  cmock_call_instance->Expected_adc_reading = adc_reading;
}

void Sharp_GP2D12_estimation_CMockExpectAndReturn(int cmock_line, unsigned char adc_reading, unsigned int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE));
  CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sharp_GP2D12_estimation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sharp_GP2D12_estimation_CallInstance = CMock_Guts_MemChain(Mock.Sharp_GP2D12_estimation_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Sharp_GP2D12_estimation(cmock_call_instance, adc_reading);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

