/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTBT7_H
#define _MOCKTBT7_H

#include "../TBT7.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockTBT7_Init(void);
void MockTBT7_Destroy(void);
void MockTBT7_Verify(void);




#define delay_new_ms_Ignore() delay_new_ms_CMockIgnore()
void delay_new_ms_CMockIgnore(void);
#define delay_new_ms_Expect(m) delay_new_ms_CMockExpect(__LINE__, m)
void delay_new_ms_CMockExpect(int cmock_line, int m);

#endif
